name: Docker Build and Push

on:
  push:
    branches:
      - main # Trigger when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_SECRET }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.USER_NAME }}/mlops:latest .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.USER_NAME }}/mlops:latest

      # Step 5: Trigger the webhook
      - name: Trigger Local System Webhook
        run: |
          curl -X POST https://fcb0-2401-4900-67b0-c9cd-9150-f484-cbe8-9992.ngrok-free.app/webhook

